### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by RealFX-Code** [GDColon/Bumpscosity-for-GD#1]
can someone explain what Bumpscosity is?

**Comment by MrNooberDude** [comment]
Stanley Parable reference

**Comment by jessiejs** [comment]
bumpscosity

**Comment by zkayns** [comment]
controls how bumpscocious the game is

**Comment by sphericle** [comment]
it allows you to adjust your bumpscosity

**Comment by GDColon** [comment]
bumpsocmpsdpoisty

**Comment by ImmediateMurderProfessionals** [comment]
> bumpsocmpsdpoisty

r/skamtebord
