### ISSUE TITLE
This isn't really related but I have an idea for something you should make on github

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [GDColon/Bumpscosity-for-GD#4]
(posting this here because github doesn't have a DM feature afaik)

GD Cologne, the most famous furry in Geometry Dash, I want you to make some sort of GD mod that gives you a Congregation jumpscare if you die.

Also even more unrelated but you should watch helluva boss on youtube it's really awesome

**Comment by GDColon** [comment]
Stop.
