### ISSUE TITLE
What does this actually change?

### ISSUE THREAD

**Issue by kingpvz** [GDColon/Bumpscosity-for-GD#5]
What does this add to the game other than the slider, whose function I've  spent hours trying to figure out?

**Comment by undefined06855** [comment]
it allows you to adjust your bumpscosity

**Comment by GDColon** [comment]
if only there was a website where you can see the source code

**Comment by kingpvz** [comment]
i read the code but i have no idea what it does anyways. does it just replace the level win text?

**Comment by undefined06855** [comment]
i need to put this in my clipboard or something man

Whenever you enter the vault of secrets, there's a 1/4 chance the text has been changed depending on your bumpscocity, and whenever you click on the keymaster there's a 1/15 chance the text will be changed.

**Comment by kingpvz** [comment]
oh, thank you kind human

**Comment by tornadoreaper** [comment]
adds a customization to adjust your bumpscosity
